toy_new_app/config/routes.rb
Rails.application.routes.draw do
	root "users#index"
	resources :microposts
	resources :users
end

toy_new_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

toy_new_app/app/models/micropost.rb
class Micropost < ApplicationRecord
	belongs_to :user

	validates :user_id, presence: true
end

toy_new_app/app/models/user.rb
class User < ApplicationRecord
	has_many :microposts
end

toy_new_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

toy_new_app/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	def index
		@microposts = Micropost.all
	end

	def show
		@micropost = Micropost.find(params[:id])
	end

	def new
		@micropost = Micropost.new
	end

	def create
		@micropost = Micropost.new(micropost_params)

		if @micropost.save
			redirect_to @micropost
		else
			render :new
		end
	end

	def edit
		@micropost = Micropost.find(params[:id])
	end

	def update
		@micropost = Micropost.find(params[:id])

		if @micropost.update(micropost_params)
			redirect_to @micropost
			else
				render :edit
		end
	end

	def destroy
		@micropost = Micropost.find(params[:id])
		@micropost.destroy

		redirect_to microposts_path
	end

	private
		def micropost_params
			params.require(:micropost).permit(:context, :user_id)
		end

end

toy_new_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to @user
		else
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			redirect_to @user
		else
			render :edit
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to root_path
	end

	private
		def user_params
			params.require(:user).permit(:name, :email)
		end

end

toy_new_app/app/helpers/application_helper.rb
module ApplicationHelper
end

toy_new_app/app/helpers/microposts_helper.rb
module MicropostsHelper
end

toy_new_app/app/helpers/users_helper.rb
module UsersHelper
end

toy_new_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyNewApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

toy_new_app/app/views/microposts/_form.html.erb
<%= form_with model: micropost do |form| %>
	<br>
	<div>
		<%= form.label :context %><br>
		<%= form.text_area :context %>
		<% micropost.errors.full_messages_for(:context).each do |message|%>
			<div><%= message %></div>
		<% end %>
	</div>
	<br>
	<div>
		<%= form.label :user_id %><br>
		<%= form.text_field :user_id%>
		<% micropost.errors.full_messages_for(:user_id).each do |message| %>
			<div><%= message %></div>
		<% end %>
	</div>
	<br>
	<%= form.submit %>
<% end %>

toy_new_app/app/views/microposts/edit.html.erb
<%=  render "form", micropost: @micropost %>
<%= link_to "back", microposts_path %>

toy_new_app/app/views/microposts/index.html.erb
<h1>Microposts</h1>

<table>
	<thead>
		<tr>
			<th>context</th>
			<th>user_id</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @microposts.each do |micropost| %>
		<tr>
			<th><%= micropost.context %></th>
			<th><%= micropost.user_id %></th>
			<th><%= link_to "show", micropost %></th>
			<th><%= link_to "edit", edit_micropost_path(micropost) %></th>
			<th><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></th>
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to "new micropost", new_micropost_path %> |
<%= link_to "users", root_path %>

toy_new_app/app/views/microposts/new.html.erb
<%= render "form", micropost: @micropost %>
<%= link_to "back", microposts_path %>

toy_new_app/app/views/microposts/show.html.erb
<h1>micropost</h1>
<div>
	<strong>Context</strong>
	<%= @micropost.context %>
</div>
<div>
	<strong>Context</strong>
	<%= @micropost.user_id %>
</div>
<%= link_to "back", microposts_path %> |
<%= link_to "edit", edit_micropost_path %>

toy_new_app/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <br>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
    <% user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <br>

  <div>
    <%= form.submit %>
  </div>

<% end %>

toy_new_app/app/views/users/edit.html.erb
<%= render 'form', user: @user %><br>
<%= link_to 'back', root_path %>

toy_new_app/app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
	<tr>
	  <th>Name</th>
	  <th>Email</th>
	  <th colspan="3"></th>
	</tr>
 </thead>

<tbody>
	<% @users.each do |user| %>
		<tr>
			<td><%= user.name %></td>
			<td><%= user.email %></td>
       <td><%= link_to 'Show', user %></td>
       <td><%= link_to 'Edit', edit_user_path(user) %></td>
       <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</tbody>
</table>
<%= link_to 'New User', new_user_path %> | 
<a href="/microposts/">microposts</a>

toy_new_app/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

toy_new_app/app/views/users/show.html.erb
<p>
	<strong>Name:</strong>
	<%= @user.name %>
</p>

<p>
	<strong>Email:</strong>
	<%= @user.email %>
</p>

<%= link_to "back", root_path %> |
<%= link_to "edit", edit_user_path(@user) %> 